version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - adetorcy
  - kamwoods
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: jupyterlab
    versions:
    - 3.0.10
    - 3.0.12
    - 3.0.13
    - 3.0.14
    - 3.0.9
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
    - 1.2.4
  - dependency-name: pillow
    versions:
    - 8.1.2
    - 8.2.0
  - dependency-name: terminado
    versions:
    - 0.9.2
    - 0.9.3
    - 0.9.4
  - dependency-name: ipython
    versions:
    - 7.21.0
    - 7.22.0
  - dependency-name: prompt-toolkit
    versions:
    - 3.0.17
    - 3.0.18
  - dependency-name: defusedxml
    versions:
    - 0.7.0
    - 0.7.1
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
    - 2.8.1
  - dependency-name: nbclient
    versions:
    - 0.5.3
  - dependency-name: anyio
    versions:
    - 2.2.0
  - dependency-name: ipykernel
    versions:
    - 5.4.3
    - 5.5.0
  - dependency-name: pyzmq
    versions:
    - 21.0.1
    - 22.0.2
    - 22.0.3
  - dependency-name: cffi
    versions:
    - 1.14.4
    - 1.14.5
  - dependency-name: matplotlib
    versions:
    - 3.3.3
    - 3.3.4
  - dependency-name: bleach
    versions:
    - 3.3.0
  - dependency-name: nest-asyncio
    versions:
    - 1.4.3
    - 1.5.1
  - dependency-name: jupyter-core
    versions:
    - 4.7.0
    - 4.7.1
  - dependency-name: prometheus-client
    versions:
    - 0.9.0
