#!/bin/bash

set -x

DATA_DIR="RevisedEDRMv1_Complete"
ZIPPED_FILES=(albert_meyers.zip andrea_ring.zip andrew_lewis.zip)

mkdir -p $DATA_DIR

# Download and expand enron files
for file in "${ZIPPED_FILES[@]}"; do
  wget -q -O "${file}" "https://s3.amazonaws.com/edrm.download.nuix.com/RevisedEDRMv1/${file}"
  unzip -qo -d $DATA_DIR "${file}"
  rm "${file}"
done
